version: '3.8'

networks:
  api-gateway:
    external: true
    name: api_gateway_api-gateway

services:
  web:
    build:
      context: .
    env_file:
      - .env
    networks:
      - api-gateway
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
